
defaults:
  - _self_
  - dataset: ucf101
  - model: resnet
  - optimizer: adam

  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog


num_workers: 10
num_epochs: 100
batch_size: 32


hydra:
  run:
    dir: /Users/piyush/outputs/hydra-tutorial/${dataset.name}_${model.name}/${now:%Y-%m-%d_%H-%M-%S}
